# Logo (Font Awesome Class)
fa_logo: fa-flask

# Header
menu:
  首页: /
  分类: /archives
  关于: /about.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/Bangood
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: 2419281635@qq.com
# rss_url: \#

# Footer About Text
# footer_about: "thnd"

# Footer Copyright Line
footer_copyright: "Bangood"
